### PR TITLE
Fix build - close #39 and #42

### LINKED ISSUE #39: Uncaught ReferenceError: System is not defined
I got following error when trying to use ng2-formly.

ng2-formly.js:1Uncaught ReferenceError: System is not defined

I'm using angular rc1 with webpack.
from this seed project https://github.com/AngularClass/angular2-webpack-starter

### PR DESCRIPTION
**Pull request by micouz**
As stated in #39 and #42 the current npm release (2.0.0-beta.2) has problems. This pull request provides a simple solution, based solely on npm and tsc. However, I ran into problems understanding the previous build system, so I happened to break it. I'm not sure how/where/if it is used, and it seems rather over-complicated, so I wondered if it would be possible to get rid of it completely.

### CODE REVIEW

**Comment by mohammedzamakhan** [comment]
@micouz the bundles folder is not being created with appropriate js and minified js files, which are used for publishing on cdnjs

**Comment by micouz** [comment]
@mohammedzamakhan Yes I missed that part. I'll add another to this PR.

**Comment by mohammedzamakhan** [comment]
for the demo to run using gulp play, I have changed the the dest folder to demo in the task ts2js and I see an error which I didn't see in the demo:

```
browser_adapter.ts:78EXCEPTION: Error in ./FormlyFieldRadio class FormlyFieldRadio - inline template:2:15BrowserDomAdapter.logError @ browser_adapter.ts:78BrowserDomAdapter.logGroup @ browser_adapter.ts:89ExceptionHandler.call @ exception_handler.ts:53(anonymous function) @ application_ref.ts:304schedulerFn @ async.ts:131SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:117NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:138NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:90ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259ZoneTask.invoke @ zone.js:423
browser_adapter.ts:78ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: '[object Object]'. Current value: 'title'BrowserDomAdapter.logError @ browser_adapter.ts:78ExceptionHandler.call @ exception_handler.ts:65(anonymous function) @ application_ref.ts:304schedulerFn @ async.ts:131SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:117NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:138NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:90ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259ZoneTask.invoke @ zone.js:423
browser_adapter.ts:78ORIGINAL STACKTRACE:
```

Can you also make sure that demo works fine with all your changes.

Thanks

**Comment by micouz** [comment]
I couldn't reproduce your error, but I had another one of my own. I then tried with a clean checkout of the branch, and for me everything works fine. Could you try again and give me the sequence of steps you take when you see the problem ?
Right now I'm concentrating on getting this PR merged to close the npm release issues, but in the not so distant future I'd like to improve the demo dev environment, using webpack-dev-server.

**Pull request merged**
