### PR TITLE
feat(demo): use webpack

### PR DESCRIPTION
**Pull request by aitboudad**
use `npm run demo` instead of `gulp play`

### CODE REVIEW

**Comment by mohammedzamakhan** [comment]
@aitboudad I am getting this error while running the demo

```
[default] /Users/zamamoha/Desktop/v2/ng2-formly/demo/hello.ts:45:12 
Cannot find name 'require'.
```

**Comment by aitboudad** [comment]
@mohammedzamakhan can you remove the compiled files (hello.js, hello.d.js) and try again ?

**Comment by mohammedzamakhan** [comment]
@aitboudad still the same

**Comment by aitboudad** [comment]
fixed by #144

**Pull request merged**
