### PR TITLE
#230 added methods to extract nested properties & create empty objects

### PR DESCRIPTION
**Pull request by Krustie101**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix. In formly form, the fieldModel method assumes that the key is not nested. This bugfix also deals with the case that the key is a nested property (including support for indices, if you really want to use this). The main code is located in the utils class.

Tests have been added for the extra code in the utils class.

**What is the current behavior? (You can also link to an open issue here)**
See #230 

**What is the new behavior (if this is a feature change)?**

**Please check if the PR fulfills these requirements**
- [x] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] A unit test has been written for this change.
- [x] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [x] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

**Please provide a screenshot of this feature before and after your code changes, if applicable.**

**Other information**:

### CODE REVIEW

**Comment by mohammedzamakhan** [comment]
Removed all the linting errors in a PR to your repo https://github.com/Krustie101/ng2-formly/pull/1

Please run the demo app, because I don't see it running with this update.

**Comment by Krustie101** [comment]
@mohammedzamakhan 
When I try to run the demo task on either my fork or the original ng2-formly code, I get the error "Uncaught Error: Can't resolve all parameters for FormlyValidationMessages:".

After debugging,  the root cause seems to be the fact that webpack loads 2 instances of the angular module. When angular tries to resolve the dependencies for FormlyValidationMessages, the instanceof `@Inject` check fails because there are 2 instances of this decorator.

So I wonder how you manage to run this demo task?

**Comment by mohammedzamakhan** [comment]
I don't get that error neither do @aitboudad. I wonder what could cause this error. I was able to run your fork as well

**Comment by franzeal** [comment]
@Krustie101 I see the same in my environment.

**Comment by mohammedzamakhan** [comment]
@divyakumarjain would know about it since he works on windows. He had made these changes in the build, try using it
https://github.com/mohammedzamakhan/ng2-formly/pull/2/files

**Comment by franzeal** [comment]
@mohammedzamakhan I was able to get it running using those changes to the files you referenced.  I did end up using the current package.json's build:bundles:compile task definition as well as adding `<script src="/build/vendor.js"></script>` to demo/index.html right before the demo script.

That got the demo application running to the point where I am getting an error stemming from a validation expression in the demo:  "Cannot set property 'custom' of undefined"

**Comment by mohammedzamakhan** [comment]
I just made the changes in my Windows VM, and I didn't get any such error.

**Comment by mohammedzamakhan** [comment]
@Krustie101 update your fork with latest, the demo application should run on windows too now 👍

**Comment by franzeal** [comment]
@mohammedzamakhan can confirm it runs in Windows now without error.  Good work and thanks!

**Comment by Krustie101** [comment]
@mohammedzamakhan  Thank you, it also works on my end.  I will now have a look at the other error.

**Comment by mohammedzamakhan** [comment]
@Krustie101 it worked for me when I did

```js
fieldModel(field: FormlyFieldConfig) {
     if (field.key && (field.fieldGroup || field.fieldArray)) {
       return getFieldModel(this.model, field, true);
     }
     return this.model;
}
```

**Comment by Krustie101** [comment]
@mohammedzamakhan That is correct. I also noticed my error, arising from the fact that I did not pay attention that you had changed the meaning of model.

**Comment by mohammedzamakhan** [comment]
LGTM 👍 

@aitboudad can you have a look at this PR and approve it?

**Comment by aitboudad** [comment]
@mohammedzamakhan I can't right now :( you can merge it if it looks good, 
I'll give my feedback, once I get some time!

**Comment by mohammedzamakhan** [comment]
@Krustie101 can you also look into using this pattern for [assignModelValue in utils.ts#L67](https://github.com/Krustie101/ng2-formly/blob/105197bfe607e06aca95af85312564e7f37b9675/src/core/utils.ts#L67) and [getValueForKey  in utils.ts#L83](https://github.com/Krustie101/ng2-formly/blob/105197bfe607e06aca95af85312564e7f37b9675/src/core/utils.ts#L83)

**Comment by Krustie101** [comment]
@mohammedzamakhan  I will do, but I am tied up tomorrow. I will look at in on Thursday.

**Comment by Krustie101** [comment]
The problem lies in the use of formControlName in the FormlyFieldRadio component, this cannot be a nested path. Like in the case of an input the formControlName should be removed and [formControl]="formControl"  should be used instead.

I also notice on line 56 of the FormBuilder (master branch) the following check: 

` if (!form.get(field.key)) {`

Should this not be 

` if (!form.get(field.key)) {`

**Pull request merged**
